defaults:
  - /callbacks@learn_callbacks: default

_target_: src.trainer.lmsb_trainer.LMSBTrainer

inner_loop_timesteps: 1000
n_outer_loops: 10 
log_interval: 100
tb_log_name: "run"
progress_bar: True
num_val_samples: null

