_target_: src.tokenizer.thought_tokenizer.create_thought_tokenizer
start_tag: <th>
end_tag: </th>

tokenizer:
  _target_: transformers.AutoTokenizer.from_pretrained
  pretrained_model_name_or_path: ${...language_model.language_model.pretrained_model_name_or_path}