defaults:
  - on_policy
  - override policy: llm_base_policy_value_model 

_target_: lm_stable_baselines.training_algorithms.ppo_on_policy.PPOOnPolicy

n_epochs: 1
target_kl: null # 0.01
clip_range: 0.2
clip_range_vf: null # Union[None, float, Schedule]
normalize_advantage: true