defaults:
  - default

test:
  accuracy:
    _target_: src.metrics.commonsense_qa_metrics.is_correct
    
# At the moment, val is only supported for src/train.py (not src/trl_train.py)
val:
  accuracy:
    _target_: src.metrics.commonsense_qa_metrics.is_correct