_target_: lm_stable_baselines.environments.LanguageModelEnv

max_tokens: ${rl_algorithm.policy.max_output_generation_length}
require_dataset: True
filler_token: -100
max_actions: 1

reasoning_step_splitter: ' ' # Splitter for reasoning steps, it can be '\n' for GSM8K, or ' ' to simply split words
ground_truth_portion: 0.4 # Portion of ground truth actions the environment pass as context. number between 0 and 1