_target_: AutoPeftModelForCausalLM.from_pretrained #only when you SAVE a PEFT/LORA model and want to reload it, not first time you want to peftify a model

pretrained_model_name_or_path: ???

#example of peft_config:
#_target_: peft.LoraConfig