_target_: src.model.components.control_token_wrappers.PauseClassifierWrapper.from_pretrained
pretrained_model_name_or_path: ???

# torch_dtype: 
#   _target_: src.utils.hydra_custom_resolvers.get_module_attr
#   module_and_attr: torch.bfloat16

post_instanciation_method_calls: []