defaults:
  - model/language_model: gpt2
  - model/tokenizer: gpt2
  - model/peft_config: default
  - generation: default

_target_: lm_stable_baselines.policies.LLMBasePolicy


learning_rate: 1e-5
features_extractor_class: ${get_class_from_name:stable_baselines3.common.torch_layers.FlattenExtractor}
features_extractor_kwargs: null
normalize_images: false
optimizer_class: ${get_class_from_name:torch.optim.Adam}
optimizer_kwargs: null
squash_output: false
filler_token: -100
max_output_generation_length: ${get_obj_attr:${rl_algorithm.policy.model.tokenizer},[model_max_length]}


