ANSWER_TEMPLATE = " ### Answer:"
QUESTION_TEMPLATE = "### INPUT: "

FEEDBACK_TEMPLATE = "### FEEDBACK: "
CORRECT_ANSWER_FEEDBACK = FEEDBACK_TEMPLATE + "Correct answer"
INCORRECT_ANSWER_FEEDBACK = FEEDBACK_TEMPLATE + "Incorrect answer"

CTRL_TOKEN_LABEL = 1
LM_HEAD_LABEL = 0
IGNORE_LABEL = -100
